# Generated by Django 3.1.3 on 2020-11-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Neverlur_Backend_API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='location_path',
        ),
        migrations.AddField(
            model_name='song',
            name='external_service_location_id',
            field=models.IntegerField(default=0),
        ),
    ]
