# Generated by Django 3.1.3 on 2020-11-26 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Neverlur_Backend_API', '0002_auto_20201126_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='location_folder_path',
        ),
    ]
