# Generated by Django 3.1.3 on 2020-11-26 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Neverlur_Backend_API', '0003_remove_album_location_folder_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='total_duration_in_minutes',
        ),
        migrations.RemoveField(
            model_name='song',
            name='total_duration_in_minutes',
        ),
    ]
