# Generated by Django 3.1.3 on 2020-11-26 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Neverlur_Backend_API', '0004_auto_20201126_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='genres',
        ),
        migrations.CreateModel(
            name='Rendering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Neverlur_Backend_API.genre')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Neverlur_Backend_API.song')),
            ],
        ),
        migrations.AddField(
            model_name='genre',
            name='songs',
            field=models.ManyToManyField(through='Neverlur_Backend_API.Rendering', to='Neverlur_Backend_API.Song'),
        ),
        migrations.AddField(
            model_name='song',
            name='genres',
            field=models.ManyToManyField(through='Neverlur_Backend_API.Rendering', to='Neverlur_Backend_API.Genre'),
        ),
    ]
